### ISSUE TITLE
DATA - Update the products URL tree structure

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#1028]
## User want

As an Analyst
I want to be clear what section of the site I'm analysing between "products" and "medicine levels in pregnancy"
So that I can analyse behaviours for different segments/areas of the website

### Data acceptance criteria

- [ ] The URL tree structure follows this format on all "products" pages: products.mhra.gov.uk/products/........

### Testing acceptance criteria

- [ ] _Tests or testing enabling changes that need to be made_

## Data - Potential impact

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
