### ISSUE TITLE
PARs  - Upload a new PAR

### ISSUE THREAD

**Issue by pataruco** [MHRA/products#375]
## User want

As a Medical Writer in the licensing team
I would like to upload a new PAR
So that I can ensure that new PARs are always available on products.mhra.gov.uk

(Linked to #397 and #398.)

### Customer acceptance criteria

- [x] Medical writers can upload a PAR PDF file to the website 
- [x] Medical writers can enter the relevant metadata about the document, such as the product name, active substances and Licence number
- [x] The new document is available on the products.mhra.gov.uk site
- [x] The PAR can be linked to one or multiple products (which will have their own PL number)
- [x] Medical writers must be logged in to the site with their MHRA account to upload and will be redirected to the sign in page if they are not. The can trigger the normal microsoft azure AD sign in from the page

Following fields are captured:
- [x] Product name per product
- [x] Active substances per product
- [x] Licence number for each product
- [x] Strength for each product
- [x] Pharmaceutical dose form for each product

### Technical acceptance criteria

- [x] PAR pdf is in blob storage after upload
- [x] PAR metadata is attached to blobs
- [x] PAR is in the Azure search index after upload
- [x] blob/metadata/search index is handled by doc-index-updater
- [x] Users accessing the app must be authenticated by being in the MHRA Azure group

### Infrastructure acceptance criteria

- [x] **terraform**: new blob storage container for temporary PAR storage
- [x] **terraform**: app registration
- [x] **terraform**: private blob container for pars-upload website
- [x] **terraform**: CDN / IP restriction / URL rewrite with SAS token
- [x] **github action**: master
   - [x] pars-upload push to non-prod private blob container
   - [ ] purges the non-prod cache of the CDN (unnecessary if we have HTML cache off)
- [x] **github action**:  branch
   - [x] doc-index-updater/pars-upload compatibility tests
   - [x] usual a11y stuff and cypress tests for pars-upload site 

 ### Data acceptance criteria

 ### Testing acceptance criteria

**Size**
XL

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate 

#813

**Comment by rjkerrison** [comment]
@TimboTambo @KaylieGreen1607 does this need to be closed/marked won't do/moved on the Github board? I can't tell where it should go to align with the physical board.

**Comment by rjkerrison** [comment]
found the physical ticket so I've put it into Discovery where this ticket is on Github right now

**Comment by roughprada** [comment]
@KaylieGreen1607 I have updated the user requirements, but from the UXD perspective, we still need to validate these ideas with Medical Writers to make sure that the way to upload the information is correct.

**Comment by roughprada** [comment]
Potential doc tille solution: **par-doc_[PLXXXXX/XXXX]-[PLXXXXX/XXXX]-[PLXXXXX/XXXX].pdf**

**Comment by roughprada** [comment]
@ainemckay @KaylieGreen1607 @rjkerrison @sgrowe We have discussed the possibility to create a single string or an array for the  PAR search based on the information we have from the metadata. We are checking with Aj what would be the preferred option and this will impact the presentation on the front end.

<img width="550" alt="Screenshot 2020-05-07 at 15 20 06" src="https://user-images.githubusercontent.com/5957010/81305571-66980180-9076-11ea-95e9-c78aa3e61eed.png">

**Comment by roughprada** [comment]
Confirmation on the licence number acronyms for the dropdown: 
<img width="820" alt="Screenshot 2020-05-15 at 11 51 39" src="https://user-images.githubusercontent.com/5957010/82049381-26580500-96ae-11ea-8aba-7f8615e1c0e0.png">

**Comment by roughprada** [comment]
We have discussed this morning the following behaviours for the PARs upload:
- add a cancel button when you have an extra product that is not required anymore
- New visuals for the extra active substances:
  - X to close if is not required
  - no labels on the extra fields
- When a user clicks edit on a product
  - the content will be populated
  - the "add other product" CTA will be hidden
  - Continue CTA aligns to the left.
- Errors will be display as per GDS guidance: https://design-system.service.gov.uk/components/error-message/
- @majikandy to add AC in relation to the new login screen
- @roughprada to provide with reviewed copy for the login screen.

**Comment by roughprada** [comment]
@sgrowe 
- X to close the active substance: https://zpl.io/Vxx6rE3
- I have change the text style on the product from bold to light, so when we are in edit mode, the title is bold and edit changes to “cancel”: https://zpl.io/Vxx6rE3
- Changed the button on edit mode too: https://zpl.io/Vxx6rE3
- Cancel on the added product so it can be removed: https://zpl.io/bzE14m8

**Comment by TimboTambo** [comment]
Issue when submitting a PAR:
<img width="595" alt="Screenshot 2020-05-28 at 16 42 38" src="https://user-images.githubusercontent.com/6436551/83165947-199fcc00-a106-11ea-8844-b66022559638.png">
<img width="638" alt="Screenshot 2020-05-28 at 16 43 44" src="https://user-images.githubusercontent.com/6436551/83165977-215f7080-a106-11ea-8316-49c3c4cd6069.png">
@sgrowe has already identified the issue and is working on a fix:
> On the review page when you click “send” it mistakenly sets the click event as the “data” for that page so when you hit send again it tries to include the click event in the form data and errors…
