### ISSUE TITLE
Product Page uses API

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#401]
### User want

**Customer acceptance criteria** 

- [x] API is in a state where it could be used easily by a third party (e.g. NHS developer)

**Technical acceptance criteria**

- [x] API allows for queries of documents for a specific product
- [ ] A list of documents should be returned in the same order as the current website
- [x] Product name should exactly match the product associated with each document.
- [ ] Documents can be filtered by one or more document type (i.e. PIL, PAR, SPC)
- [ ] The output of the API should include pagination.
- [ ] website uses this when feature query param `useGraphQl=true` set 

This relates to #454.

**Data acceptance criteria**

**Testing acceptance criteria** 

- [ ] https://mhraproductsnonprod.z33.web.core.windows.net/product/?product=CO-CODAMOL%208MG%2F500MG%20TABLETS&useGraphQl=true fetches results from graphQl

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
Currently failing due to an issue where a variable named `offset` is being called `skip` by the website. Will be fixed by #754 .

**Comment by majikandy** [comment]
# QA
Working as expected with and without useGraphQl=true

GraphQl returns the data in a slightly different order but the website returns it in the same order with and without the flag and the client side filtering by doc type still works.
