### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Create service retrieves files from Sentinel

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#425]
### User want

As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**

- [x] Create message retrieved (prerequisite on #421)
- [ ] SFTP server credentials are read from environment variables
- [ ] Create service retrieves file at path given in create message from configured SFTP server

**Data acceptance criteria**

**Testing acceptance criteria** 

- [ ] Integration tests use a local SFTP server
- [ ] Integration tests cover process from calling document manager endpoint to retrieving the file from SFTP

**Size**
L

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by sgrowe** [comment]
QA'd and looks good
