### ISSUE TITLE
AUTOMATIC BATCH PROCESS - State manager responds to requests by providing state of file

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#434]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
- [ ] State manager returns a file processing status in response to an API request.
- [ ] ~It indicates an error if the file cannot be found in the k:v store.~ As part of the design, it is possible that the state manager is legitimately called before it has seen a valid key. In the case where a valid key is given but no value is found for that key, it will return _NotFound_.
- [ ] _Accepted_, _Done_, _Error_ are valid states for the job to be in.
- [ ] Deserialisation from Redis works

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
