### ISSUE TITLE
Add Health Endpoint to Stub Document Manager API

### ISSUE THREAD

**Issue by m-doughty** [MHRA/products#452]
Further to conversations with Dilu, we need to add a health endpoint.

**Acceptance criteria:**

- [x] Should be accessible at `/health`
- [x] Should require authentication
- [x] Should return OK with no contents
