### ISSUE TITLE
Integration tests for the doc-index-updater

### ISSUE THREAD

**Issue by rjkerrison** [MHRA/products#468]
# Integration tests for the doc-index-updater

This is all about creating integration tests which should have been covered in #434, #435, #444, #456.

## User want

As a Products team member
I want to know when someone has broken functionality in the doc-index-updater
So that I can prevent it from causing issues in production

### Customer acceptance criteria

People uploading documents to Sentinel want the upload service to be robust, which means well-tested.

### Technical acceptance criteria

Tests should cover:

- [ ] Spinning up a redis server as part of the 
- [ ] Setting a status using the status setting endpoint
- [ ] Getting a job status using the get status endpoint
- [ ] Calling the delete endpoint and seeing the job status updated
- [ ] Calling the create endpoint and seeing the job status updated

### Testing acceptance criteria

- [ ] Tests exist.
- [ ] They run.
- [ ] They pass.
- [ ] They're understandable.
- [ ] They fail when code is changed that breaks the functionality they purport to cover.

### Exit Criteria met

- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
