### ISSUE TITLE
DATA - Add the event date to the data layer

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#483]
### User want
As an analyst I would like to grab the date in the Data Layer, so that it saves hours in downloading data.

### Acceptance Criteria

**Customer acceptance criteria** 
N/A
**Technical acceptance criteria**

- [x] Whenever we update the `dataLayer` in `Events.ts`, we add a field which contains the current date
- [x] Date format is `yyyy-mm-dd`

**Data acceptance criteria**
be able to see the date as one of the data layer variable
being able to create a tag with that date data layer variable

**Testing acceptance criteria** 
have the date show in the tag in Google Analytics

**Data - Potential impact**
save a lot of data upload and modelling time
**Size**
XS

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate.

**Comment by m-doughty** [comment]
Have tested the PR, it works as I assume is expected on the sandbox session.
