### ISSUE TITLE
Remove completed messages from Service Bus

### ISSUE THREAD

**Issue by rjkerrison** [MHRA/products#493]
## Remove completed messages from Service Bus

As a drug scientist creator regulator person
I want to upload new or destroy old documents
So that patients have access to the best data

### Customer acceptance criteria

- [ ] Jobs for creation are eventually picked up
- [ ] Jobs for deletion are eventually picked up

### Technical acceptance criteria

- [ ] We remove from the Service Bus messages which we know have been successful
- [ ] We retain on the Service Bus messages which we do not know have been successful

### Testing acceptance criteria

- [ ] Tests cover the removal of messages
- [ ] Tests cover the ability to pick up a message twice when removal hasn't occurred

## Data - Potential impact

**Size**
S

**Value**
Huge

**Effort**
Is this different from Size?

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
For this, I will have to make changes to the _AzureSDKForRust_ crate that we're using. I'll get these into [the Red Badger fork][RB Azure crate].

[RB Azure crate]: https://github.com/RedBadger/AzureSDKForRust
