### ISSUE TITLE
AUTO BATCH IMPORT - Basic Auth

### ISSUE THREAD

**Issue by m-doughty** [MHRA/products#507]
## User want

As a user
I want to call `doc-index-updater`
So that it is more difficult to forge requests

## Acceptance Criteria

- [ ] Correct username & password should be defined in env
- [ ] Requests without correct username & password (HTTP Basic Auth) should be declined

### Customer acceptance criteria

- [ ] Requests without correct username & password (HTTP Basic Auth) should be declined

### Technical acceptance criteria

- [ ] Correct username & password should be defined in env

### Data acceptance criteria

N/A

### Testing acceptance criteria

See acceptance criteria.

## Data - Potential impact

N/A

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
Minor issues from QA:

* Response to a request with no auth headers is 500 instead of 401.
* Response to a request with bad auth details in 500 instead of 403 or 401 (I can't remember which is the proper one in this scenario).

However, these responses have bodies reading `Unhandled rejection: AuthenticationFailed`, so they're OK for an MVP.

**Comment by m-doughty** [comment]
> Minor issues from QA:
> 
> * Response to a request with no auth headers is 500 instead of 401.
> * Response to a request with bad auth details in 500 instead of 403 or 401 (I can't remember which is the proper one in this scenario).
> 
> However, these responses have bodies reading `Unhandled rejection: AuthenticationFailed`, so they're OK for an MVP.

These issues relate to the routing & rejection handling issues which are captured in #534, and which I started a thread about on Slack earlier today. The way we have currently implemented routing, there just isn't a sane way to support rejection handling, and I think the compromise which will need to be made is that JSON & XML content-type headers will both need to be set explicitly and we will route like this (pseudo):

```
serve
  content type & accept = xml
    ... xml routes on 'or' ...
    handle rejections
  content type & accept = json
    ... json routes on 'or' ...
    handle rejections
  with logger
```
