### ISSUE TITLE
Observability | Structured logs for doc index updater

### ISSUE THREAD

**Issue by pataruco** [MHRA/products#523]
## User want

Part of #408 

As a tech user 
I want set structured logs for doc index updater
So I can have meaningful data to monitor/alert/ debug

### Technical acceptance criteria

Should have structured logs with this suggested schema

```json
{
  "timestamp": "2020-03-18T13:13:05.442Z",
  "service_name": "medicines/doc-index-updater",
  "correlation_id": "92bb6eb5-b8c8-4ad3-8e5a-65bb71e34729",
  "event": {
    "label": "DOCUMENT_MANAGER_CREATE",
    "payload": {
      // 
    }
  },
  "level": "INFO"
}

```

for the following events/interactions:

- [ ] Sentinel  <--> Adding a job to the Document Manager
- [ ] Document Manager  <--> Service bus
- [ ] Service bus  <--> Check in 
- [ ] Check in   <--> Sentinel file system
- [ ] Check in   <--> blob storage
- [ ] Sentinel  <--> Checking job status
- [ ] State manager  <--> Redis
- [ ] Serve logs from warp
- [ ] Delete from Blob Storage
- [ ] Delete from Index
- [ ] Create from Index

Note the following:

- [ ] In the event of everything working as expected, log to **DEBUG**.
- [ ] In the event of something which presents a possible but recoverable problem, log to **INFO**.
- [ ] In the event of something causing an individual job to be impossible to process, log to **WARN**.
- [ ] In the event of something fatal for all jobs occurring, log to **ERROR**.

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [ x] Backlog
- [ x] Discovery
- [x ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
@majikandy @sgrowe I've added ACs about the log level, please check they make sense

**Comment by craiga** [comment]
It doesn't look like there's a message for "Sentinel <--> Adding a job to the Document Manager".  There's an info log from warp though.

```
{
  "timestamp": "2020-03-26T14:14:58.296065+00:00 ",
  "level": "INFO",
  "target": "doc_index_updater",
  "fields": {
    "message": "127.0.0.1:64402 \"POST /documents HTTP/1.1\" 200 \"-\" \"Paw/3.1.10 (Macintosh; OS X/10.15.3) GCDHTTPRequest\" 966.171445ms",
    "log.target": "doc_index_updater",
    "log.module_path": "warp::filters::log",
    "log.file": "/Users/craiga/.cargo/git/checkouts/warp-6bcdb00bfbe6cee5/a2d40cd/src/filters/log.rs",
    "log.line": 37
  }
}
```

**Comment by majikandy** [comment]
In trying to setup a structure for these messages, it deviated slightly from the once pedro put in the card, but should cover intitally message and correlation id. 

I think we could easily add label in there but in the code the idea of the usage of the structured logging would always be

I think we could add a wrapper method to enforce the structure but for now it relies on everyone doing this

`tracing::error!(message = "the message", correlation_id="the job id")`

Currently a json log entry will look like this:-
```
{
      "timestamp":"2020-03-23T16:17:18.317941+00:00 ",
      "level":"ERROR",
      "span":  {
         "name": "create_service_worker", 
         "state_manager":"StateManager { 
              client: Client { 
                   connection_info: ConnectionInfo { addr: Tcp(\"127.0.0.1\", 6379), db: 0, passwd: None } 
              } 
          }",
          "time_to_wait":"30s"
        },
        "target":"doc_index_updater::service_bus_client",
        "message":"Error Couldn't retrieve file: [-31] Failed opening remote file",
        "correlation_id":"8aacd062-8179-4852-9f9d-58d4c7f961d3"
}
```

but I just spotted that this is gonna dump the redis password in there!  This is bad - we can add the skip_field attribute to that password.....

**Comment by majikandy** [comment]
This is now ready for retest - https://github.com/MHRA/products/pull/594 addresses the structure inconsistencies
