### ISSUE TITLE
Sane error handling & routing

### ISSUE THREAD

**Issue by m-doughty** [MHRA/products#534]
## User want

As a _user_
I want _to see sensible errors_
So that _I understand what's going wrong_

## Acceptance Criteria

- [ ] Rewrite our routing so that we can implement a rejection handler for both JSON & XML requests;
- [ ] Implement custom Rejections where it makes sense to give the user greater visibility of what went wrong;
- [ ] Implement a rejection handler which understands all of the Rejections it could get and how to convert them to a meaningful error & status code;
- [ ] Use that rejection handler (`.recover(...)` in warp) to handle all rejections.

### Customer Acceptance Criteria

- [ ] Customer should get useful error messages;
- [ ] Customer should get meaningful status codes.

### Technical acceptance criteria

- [ ] Our routing should be optimized so that if, for example, `Content-Type` is set to `application/xml`, we don't try the JSON routes, same for if the Auth header is empty;
- [ ] We should have observability of how failures are happening.

### Data acceptance criteria

- [ ] N/A

### Testing acceptance criteria

- [ ] Needs Discovery

## Data - Potential impact

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
