### ISSUE TITLE
Substance page uses API

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#620]
### User want

As a 3rd party user I would like to able to access substance information through an API, so that I don't have to scrape the website and have easy access to the information.

### Acceptance Criteria

**Customer acceptance criteria** 

- [ ] A third party user can access the products API. It should be self-documenting to a user who is familiar with GraphQL.
- [ ] Substance page of the site can load a complete, alphabetised list of products for a given substance, as is the current behaviour

**Technical acceptance criteria**

- [ ] The public-facing web site makes use of the products API to retrieve a list of products which use a substance.
- [ ] The function of the web site should be otherwise unchanged.
- [ ] The API and doc index updater should share an implementation of the rust Azure search client.
- [ ] The Cypress tests are modified to reflect the use of the API.
- [ ] ~~Self-documenting API is linked to from GitHub so it can be discovered by a third-party developer.~~ (see #701)

**Data acceptance criteria**

- [ ] ~~The fact the API exists should be publicised somewhere, so people know where to access it.~~ (see #701)

**Testing acceptance criteria** 
- [ ] https://mhraproductsnonprod.z33.web.core.windows.net/substance/?substance=CODEINE%20PHOSPHATE%20HEMIHYDRATE&useGraphQl=true fetches products for that substance from graphQl

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
Now that the search client has been split into a separate crate, there are now two parallelizable pieces of work:

 * making use of the new search client crate in the API; and
 * making use of the API from the frontend.

**Comment by majikandy** [comment]
QA

self documenting part was good and led to easily using graphiql and then supplying this query

```
{
  substance(name: "CAFFEINE") {
    products
  }
}

```

it then fails to actually run the query and get results -> this is the error

```
"upstream connect error or disconnect/reset before headers. reset reason: connection termination"
```

devtools
```
Summary
URL: https://medicines-api.test.mhra.gov.uk/graphql
Status: 503
Source: Network
Address: 51.132.171.245:443
Initiator: 
graphiql:1:882


Request
:method: POST
:scheme: https
:authority: medicines-api.test.mhra.gov.uk
:path: /graphql
Accept: application/json
Content-Type: application/json
Origin: https://medicines-api.test.mhra.gov.uk
Content-Length: 966
Accept-Language: en-gb
Host: medicines-api.test.mhra.gov.uk
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
Referer: https://medicines-api.test.mhra.gov.uk/graphiql
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

Response
:status: 503
Content-Length: 95
Content-Type: text/plain
Date: Thu, 23 Apr 2020 14:01:54 GMT
Server: istio-envoy
x-envoy-upstream-service-time: 277

Request Data
MIME Type: application/json
Request Data: 

```

**Comment by craiga** [comment]
@majikandy You need to specify what you want to see in each product.

```
{
  substance(name: "CAFFEINE") {
    products {
      name
    }
  }
}
```

**Comment by majikandy** [comment]
Ah yes, thanks @craiga it all works, the name bit wasn't naturally discoverable but seems if one knows graphiql then they would recognise the error to just mean the query was incomplete and since the AC says it is for a user familiar with GraphQL this is fine

**Comment by majikandy** [comment]
also noticed favicon.ico  gets a 404  (in the devtools network tab) when testing this

**Comment by majikandy** [comment]
I guess it would be nice if the useGraphQl feature toggle was case insensitive, and also if it could then append to all links from that point forward (perhaps do that on the next page to adopt this). But otherwise this is a QA pass
