### ISSUE TITLE
Search results page uses API

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#621]
### User want
As a 3rd party user I would like to able to access search information through an API, so that I don't have to scrape the website and have easy access to the information.

### Acceptance Criteria

**Customer acceptance criteria** 

- [x] A third party user can access the documents API. It should be self-documenting to a user who is familiar with GraphQL.
- [x] Search results page of the site can load a complete list of documents for a given search term, as is the current behaviour.
- [x] Document lists can be filtered by document type, as is the current behaviour.

**Technical acceptance criteria**

- [x] The public-facing web site makes use of the documents API to retrieve a list of documents which are relevant to a search term.
- [x] The public-facing web site makes use of the documents API to filter those lists of documents.
- [x] The function of the web site should be otherwise unchanged.
- [x] The API and doc index updater should share an implementation of the rust Azure search client.
- [x] The Cypress tests ~are modified~ are added to reflect the use of the API. (Old ones can stay with the feature flag off until we remove the old direct-to-Azure features.)

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by majikandy** [comment]
## QA
Results fail to load when using GraphQl

@majikandy   9:24 AM
https://mhraproductsnonprod.z33.web.core.windows.net/search/?search=caffeine&page=1&useGraphQl=true

400 bad request for the graphql call

@rjkerrison  9:25 AM
`{"errors":[{"message":"Variable \"documentTypes\" of type \"[String!]\" used in position expecting type \"[DocumentType!]\"","locations":[{"line":2,"column":57},{"line":3,"column":79}]}]}`

Suggest when we fix we add some kind of protection for the contract between web and api.

**Comment by rjkerrison** [comment]
Thanks @majikandy. That bug should be fixed by #753.

**Comment by majikandy** [comment]
## QA 2

```
 ➜  ~ curl https://mhraproductsnonprod.z33.web.core.windows.net/search/\?search\=caffeine\&page\=1\&useGraphQl\=true > graphql.txt
 ➜  ~ curl https://mhraproductsnonprod.z33.web.core.windows.net/search/\?search\=caffeine\&page\=1 > search.txt  
 ➜  ~ diff graphql.txt search.txt 
 ➜  ~ 
```
PASS

**Comment by majikandy** [comment]
on second thoughts, those curls above not good enough as they are both the cookie box

**Comment by majikandy** [comment]
QA 2

Fail when filtering by document type using graphql

https://mhraproductsnonprod.z33.web.core.windows.net/search/?search=caffeine&page=1&doc=Spc&useGraphQl=true

```
{
    "errors": [
        {
            "message": "Variable \"$documentTypes\" got invalid value. In element #0: Invalid value for enum \"DocumentType\".",
            "locations": [
                {
                    "line": 2,
                    "column": 57
                }
            ]
        }
    ]
}
```

**Comment by rjkerrison** [comment]
Thanks. #754 should handle it.

**Comment by majikandy** [comment]
# QA

Now working as expected 👍 

Moving to ready for UAT.
