### ISSUE TITLE
Separate deleting blobs process from deleting from index process

### ISSUE THREAD

**Issue by m-doughty** [MHRA/products#667]
## User want

As a _technical user_
I want _to properly understand error states_
So that _I am able to debug where edge cases are failing_

## Acceptance Criteria

- [ ] New workflow for deletes:

- Receive message to delete document
- Look up in index
- Delete blob
- If successful, dispatch message to delete in index
- Receive message to delete index
- Delete index
- Mark as done

### Customer acceptance criteria

- [ ] _If a blob doesn't exist but a search index entry does, the blob not being found should trigger a 404._

## Data - Potential impact

**Size**
S

**Value**
S

**Effort**
S

### Exit Criteria met 
- [x] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
