### ISSUE TITLE
Distribution list for alerts

### ISSUE THREAD

**Issue by craiga** [MHRA/products#725]
## User want

As a technical support group
I want alerts sent to my email address
So I can be aware of issues as they arise.

## Acceptance Criteria

- [ ] We have a distribution list (Andy Snow to create) on AD
- [ ] Alerts are sent to that distribution list
- [ ] Can be sent from external email addresses (Azure)

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
