### ISSUE TITLE
Upload new PAR

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#756]
## User Want

As a Medical Writer in the licensing team
I would like to upload a new PAR
so that it is available on products.mhra.gov.uk

### Technical acceptance criteria

- [ ] PAR pdf is in blob storage after upload
- [ ] PAR metadata is attached
- [ ] PAR is in the search index
- [ ] blob/metadata/search index is handled by doc-index-updater

### Customer acceptance criteria

- [ ] Medical writers can upload a file which will then be surfaced on products.mhra.gov.uk
- [ ] The PAR can be linked to one or multiple products (which will have their own PL number)
- [ ] PAR has product name
- [ ] PAR has active substances, something about TMS list (unsure what this is, #no-acronyms)
- [ ] PAR has one or more PLs / NR (unsure what this is) / THR (unsure what this is)

## Data - Potential impact

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
> 4. When a PL number is searched for on the website it pulls the relevant PAR, SPC and PIL into the search results

Does "the website" refer to products.mhra.gov.uk, or a PARs upload website?

> 5. The data is stored to be able to be resurfaced onto the website at some point.

What data are stored?

**Comment by rjkerrison** [comment]
Closing as duplicate of #375.
