### ISSUE TITLE
PARS - Design review for search results display

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#881]
TASK
Design tweaks needed to the search results display, so that they are in line with SPC / PILs

### Acceptance Criteria
- [ ] The commas are removed from the between product name, dose, strength etc
- [ ] There is a dash between the name and the PL number (example...... Ibuprofen 200mg Tablets (Ibuprofen) - PL 17907/0160)
**Customer acceptance criteria** 

**Technical acceptance criteria**

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
