### ISSUE TITLE
PARs - User guide

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#883]
### User want
As a Medical Writer I would like to read a user guide on how to upload and amend PARs, so that I'm fully informed and can refer back this when i NEED HELP

### Acceptance Criteria

**Customer acceptance criteria** 
- [ ] Step by step guide on uploading a new PAR
- [ ] Step by step guide on uploading an amended PAR
- [ ] Details on how to access log files for auditing

**Technical acceptance criteria**

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
