### ISSUE TITLE
Automatically extend PAR login token

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#884]
## User want

As a user
I want to remain logged in to the portal
So that I can go away, come back and still submit without authentication issues

## Acceptance Criteria

_Fill/delete these as appropriate. Add multiple criteria under a heading if necessary.

### Customer acceptance criteria

- [ ] _What the customer can check_

### Technical acceptance criteria

- [ ] _Technical things that have to happen_

### Data acceptance criteria

- [ ] _Data that needs to be collected_

### Testing acceptance criteria

- [ ] _Tests or testing enabling changes that need to be made_

## Data - Potential impact

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
