### ISSUE TITLE
PARs - File upload on every edit

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#885]
### User want
As a Medical Writer I would like my file to remain uploaded even after editing my upload details

### Acceptance Criteria

**Customer acceptance criteria** 
- [ ] Document remains uploaded following edit of details 
- [ ] Document remains uploaded following deletion of another PARs document 

**Technical acceptance criteria**

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
