### ISSUE TITLE
Switch products site to use medicines API

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#900]
## User want

As a business
I want to use the medicines API for the products site
So that I can have better control over how data is served rather than using the search service directly

## Acceptance Criteria

- [x] Search on the products site should call the Medicines API instead of the Azure search service
- [x] It should be easy to update the site deployment workflow in order to toggle between the Medicines API and the Azure search service

## Testing

- Go to non-prod products site and open the dev tools
- Make a search and ensure that the medicines API endpoint is called and that results are returned

## Data - Potential impact

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
