### ISSUE TITLE
Convert PARs site to typescript

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#984]
## Convert PARs site to typescript

As a user
I want to be able to use older browsers like IE11
So that I can use the same browser that I use for other things

## Acceptance Criteria

Site builds to target ES5 for older browsers. The easiest way to do this is to use typescript with the related configuration.

### Customer acceptance criteria

- [ ] _What the customer can check_

### Technical acceptance criteria

- [ ] _Technical things that have to happen_

### Data acceptance criteria

- [ ] _Data that needs to be collected_

### Testing acceptance criteria

- [ ] _Tests or testing enabling changes that need to be made_

## Data - Potential impact

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate
